// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3iKRzVBKe8nu-lXtoQowXCcLBb83vBnM',
    appId: '1:946309065999:web:0d0282928b06654965a27a',
    messagingSenderId: '946309065999',
    projectId: 'todo-app-59299',
    authDomain: 'todo-app-59299.firebaseapp.com',
    storageBucket: 'todo-app-59299.firebasestorage.app',
    measurementId: 'G-7Q6H26BKLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHRurt_eaFZ3lfwzLRaThnndL_-7b-QfU',
    appId: '1:946309065999:android:fadf9c4d2011794b65a27a',
    messagingSenderId: '946309065999',
    projectId: 'todo-app-59299',
    storageBucket: 'todo-app-59299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrAF943WcNjTjrdfH8lQ937gd7EmoBTuc',
    appId: '1:946309065999:ios:c6ada7bd0ed1464b65a27a',
    messagingSenderId: '946309065999',
    projectId: 'todo-app-59299',
    storageBucket: 'todo-app-59299.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrAF943WcNjTjrdfH8lQ937gd7EmoBTuc',
    appId: '1:946309065999:ios:c6ada7bd0ed1464b65a27a',
    messagingSenderId: '946309065999',
    projectId: 'todo-app-59299',
    storageBucket: 'todo-app-59299.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3iKRzVBKe8nu-lXtoQowXCcLBb83vBnM',
    appId: '1:946309065999:web:340ee35d965f07ad65a27a',
    messagingSenderId: '946309065999',
    projectId: 'todo-app-59299',
    authDomain: 'todo-app-59299.firebaseapp.com',
    storageBucket: 'todo-app-59299.firebasestorage.app',
    measurementId: 'G-6JBQ0VS2VR',
  );
}
